### PR TITLE
Support playback speed

### PR DESCRIPTION
**Pull request by marcopar**
Added preference to change the playback speed in steps from 0.25 to 4. Tried also 5 but it stutters a lot on my TV in 4K HDR....it may be that maximum play speed is device dependent and network bandwidth dependent

### CODE REVIEW

**Comment by marcopar** [comment]
Looks like there's an issue when the video ends. It doesn't switch to the next one and remains stuck on the last frame.
I'll take a look.

**Comment by theothernt** [comment]
Sounds like a great feature to add - let me know if you fix the issue you mention?

**Comment by theothernt** [comment]
@marcopar I think I may know what the bug is. For the videos to fade, a timer is set to the length of the video minus the fade time. When you increase the video playback speed, the length of the video may still be reported as 100%.

So if a video is 1 min long, playing at 2x speed, the video will finish playing after 30 secs then stop until 58secs when the fade starts.

Anyway, just a guess :)

**Comment by marcopar** [comment]
Looks like that's the case, if you wait enough it will fade to the next video

**Comment by marcopar** [comment]
Fixed

**Comment by theothernt** [comment]
Ok, I'll probably merge this towards the end of the week (24/09/2021) assuming you find no issues, etc

**Comment by theothernt** [comment]
Happy to accept the PR if you'd like to have a go at the merg?

**Comment by marcopar** [comment]
I can't see what conflicts are there

**Comment by theothernt** [comment]
On the GitHub website, you can view your own fork on this repo - then click on 'Fetch upstream', you should be able to handle the merge + fixes from there.

**Comment by marcopar** [comment]
uh...i didn't notice they added a fetch upstream magic button....great
i'll take a look asap

**Comment by marcopar** [comment]
it was a wild journey in git space but i think i merged correctly

**Comment by theothernt** [comment]
Thanks for all that work, I'll merge it now and start testing!

**Pull request merged**
